name: NexEngine
main: su.nexmedia.engine.NexEngine
version: '${project.version}'
description: Plugin Engine
author: NightExpress
softdepend: [ Vault]
api-version: 1.17
load: STARTUP
folia-supported: true
libraries:
  - com.zaxxer:HikariCP:5.1.0
  - it.unimi.dsi:fastutil:8.5.13
  - org.xerial:sqlite-jdbc:3.45.3.0
  - com.google.guava:guava:33.1.0-jre